from tkinter import *
from tkinter import filedialog, Text
from PIL import ImageTk, Image

# Pictures ready to be called with Dir locations later in program
disc = ImageTk.PhotoImage(Image.open('Assets/discord.png'))
rs = ImageTk.PhotoImage(Image.open('Assets/runescape.png'))
lol = ImageTk.PhotoImage(Image.open('Assets/league.png'))
chrome = ImageTk.PhotoImage(Image.open('Assets/chrome.png'))
minecraft = ImageTk.PhotoImage(Image.open('Assets/minecraft.png'))
photoshop = ImageTk.PhotoImage(Image.open('Assets/photoshop.png'))
mail = ImageTk.PhotoImage(Image.open('Assets/mail.png'))
notepad = ImageTk.PhotoImage(Image.open('Assets/notepad.png'))
spotify = ImageTk.PhotoImage(Image.open('Assets/spotify.png'))
finalcut = ImageTk.PhotoImage(Image.open('Assets/finalcut.png'))
photo = ImageTk.PhotoImage(Image.open('Assets/photos.png'))
xcode = ImageTk.PhotoImage(Image.open('Assets/Xcode.png'))
pycharm = ImageTk.PhotoImage(Image.open('Assets/PyCharm CE.png'))
zoom = ImageTk.PhotoImage(Image.open('Assets/zoom.png'))
vscode = ImageTk.PhotoImage(Image.open('Assets/vscode2.png'))
safari = ImageTk.PhotoImage(Image.open('Assets/Safari.png'))
subtxt = ImageTk.PhotoImage(Image.open('Assets/Sublime Text.png'))
itunes = ImageTk.PhotoImage(Image.open('Assets/iTunes.png'))
news = ImageTk.PhotoImage(Image.open('Assets/News.png'))
automator = ImageTk.PhotoImage(Image.open('Assets/Automator.png'))
books = ImageTk.PhotoImage(Image.open('Assets/Books.png'))
calculator = ImageTk.PhotoImage(Image.open('Assets/Calculator.png'))
calendar = ImageTk.PhotoImage(Image.open('Assets/Calendar.png'))
chess = ImageTk.PhotoImage(Image.open('Assets/Chess.png'))
contacts = ImageTk.PhotoImage(Image.open('Assets/Contacts.png'))
dashboard = ImageTk.PhotoImage(Image.open('Assets/Dashboard.png'))
dictionary = ImageTk.PhotoImage(Image.open('Assets/Dictionary.png'))
facetime = ImageTk.PhotoImage(Image.open('Assets/FaceTime.png'))
home = ImageTk.PhotoImage(Image.open('Assets/Home.png'))
keynote = ImageTk.PhotoImage(Image.open('Assets/Keynote.png'))
launchpad = ImageTk.PhotoImage(Image.open('Assets/Launchpad.png'))
siri = ImageTk.PhotoImage(Image.open('Assets/Siri.png'))
steam = ImageTk.PhotoImage(Image.open('Assets/Steam.png'))
piedpiper = ImageTk.PhotoImage(Image.open('Assets/piedpiper.png'))
messages = ImageTk.PhotoImage(Image.open('Assets/messages.png'))
zoom = ImageTk.PhotoImage(Image.open('Assets/zoom.png'))
